#!/usr/bin/env python3
"""Render a stable Homebrew formula from the verified release checksums."""

import argparse
from pathlib import Path
import re
import sys

from release_common import archive_checksums


def render(tag, checksums, current=None):
    if not re.fullmatch(r"v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)", tag):
        raise ValueError("Homebrew requires a stable vMAJOR.MINOR.PATCH tag")
    version = tag[1:]
    if current is not None and current.exists():
        match = re.search(r'^  version "([0-9]+\.[0-9]+\.[0-9]+)"$', current.read_text(), re.MULTILINE)
        if not match:
            raise ValueError("cannot determine the existing formula version")
        if tuple(map(int, match[1].split("."))) > tuple(map(int, version.split("."))):
            raise ValueError("refusing to downgrade the existing formula")
    hashes = archive_checksums(tag, checksums)
    lines = [
        "# Generated by rebaze/preflight's release workflow. DO NOT EDIT.",
        "class Preflight < Formula",
        '  desc "Local policy and test feedback before opening a pull request"',
        '  homepage "https://github.com/rebaze/preflight"',
        f'  version "{version}"',
        '  license "Apache-2.0"',
    ]
    for os, block in (("darwin", "on_macos"), ("linux", "on_linux")):
        lines += ["", f"  {block} do"]
        for arch, cpu in (("amd64", "on_intel"), ("arm64", "on_arm")):
            name = f"preflight_{version}_{os}_{arch}.tar.gz"
            url_name = name.replace(version, "#{version}", 1)
            lines += [f"    {cpu} do",
                      f'      url "https://github.com/rebaze/preflight/releases/download/v#{{version}}/{url_name}"',
                      f'      sha256 "{hashes[name]}"', "    end"]
        lines += ["  end"]
    lines += [
        "", '  depends_on "conftest"', '  depends_on "git"', "",
        "  def install", '    bin.install "preflight"',
        '    pkgshare.install Dir["share/preflight/*"]', "  end", "",
        "  def caveats", "    <<~EOS",
        "      Profiles and policies: #{pkgshare}",
        "      Docker with a Linux daemon is required for prepare and test execution.",
        "      Select the policy baseline and Conftest executable explicitly at init.",
        "    EOS", "  end", "",
        "  test do",
        '    assert_match "preflight #{version}", shell_output("#{bin}/preflight version")',
        '    assert_path_exists pkgshare/"profiles/invoicex-frontend.json"',
        '    assert_path_exists pkgshare/"policy/main.rego"', "  end", "end", "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tag", required=True)
    parser.add_argument("--checksums", type=Path, required=True)
    parser.add_argument("--current", type=Path)
    args = parser.parse_args()
    try:
        sys.stdout.write(render(args.tag, args.checksums, args.current))
    except (OSError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
